# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='shirt_size',
            field=models.CharField(choices=[('s', 'small'), ('m', 'medium')], default='s', max_length=1),
        ),
    ]
