# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0002_person_shirt_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myperson',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('nails.person',),
        ),
    ]
