# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0003_myperson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Myperson',
        ),
    ]
