# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20160302_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='questionx',
            new_name='question',
        ),
    ]
