# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-04 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delic',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
    ]
